package com.elearny.entity;

public enum NotificationType {
    ENROLLMENT_CONFIRMATION, CERTIFICATE_ISSUED, FORUM_REPLY, REFUND_STATUS,
    LIVE_SESSION_BOOKING, LIVE_SESSION_REMINDER, WAITLIST_CLAIM_OFFER,
    COUPON_EXPIRING, TA_INVITATION, PASSWORD_RESET, GENERAL
}
