services:
  - type: web
    name: elearny-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VERCEL_WEB_URL
        sync: false
