'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { 
  BookOpen, 
  Award, 
  ShieldCheck, 
  Code, 
  Sparkles, 
  ArrowRight, 
  Users, 
  CheckCircle2, 
  Zap, 
  PlayCircle, 
  Lock,
  Phone,
  Mail,
  Clock,
  Search,
  ChevronDown,
  ChevronRight,
  Layers,
  Star,
  Send,
  HelpCircle,
  Activity
} from 'lucide-react';

export default function Home() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeTab, setActiveTab] = useState<'all' | 'backend' | 'ai' | 'cloud'>('all');

  const faqs = [
    {
      q: 'How does automated exam proctoring work on eLearny?',
      a: 'eLearny monitors browser integrity by enforcing full-screen mode, logging window blur/tab switches with timestamps, and disabling copy-paste during attempts. Server-side grading evaluates submissions instantly without trusting client scores.',
    },
    {
      q: 'Are certificates verifiable by third-party employers?',
      a: 'Yes! Every certificate generated by eLearny contains a unique verification code and QR code powered by Apache PDFBox. Employers can verify certificate validity without logging in at /certificates/verify/{code}.',
    },
    {
      q: 'How does the embedded code playground execute code?',
      a: 'Code exercises run in isolated, secure sandboxes powered by a self-hosted Judge0 execution engine. Students write code directly in the lesson view and get real-time compiler feedback.',
    },
    {
      q: 'Can instructors manage courses and pricing independently?',
      a: 'Approved instructors have full control over course creation, module structure, pricing, coupon discounts, drip content schedules, and personal revenue analytics.',
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans selection:bg-primary/20 selection:text-primary">
      {/* 1. Top Utility Info Bar (Porto Utility Header Pattern) */}
      <div className="bg-secondary text-white text-xs py-2 border-b border-white/10 hidden md:block">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between">
          <div className="flex items-center space-x-6">
            <div className="flex items-center space-x-1.5 opacity-90">
              <Clock className="w-3.5 h-3.5 text-primary" />
              <span>Mon - Sat 8:00 AM - 8:00 PM EST</span>
            </div>
            <div className="flex items-center space-x-1.5 opacity-90">
              <Phone className="w-3.5 h-3.5 text-primary" />
              <a href="tel:+18005550199" className="hover:underline">+1 (800) 555-ELEARNY</a>
            </div>
            <div className="flex items-center space-x-1.5 opacity-90">
              <Mail className="w-3.5 h-3.5 text-primary" />
              <a href="mailto:support@elearny.com" className="hover:underline">support@elearny.com</a>
            </div>
          </div>

          <div className="flex items-center space-x-4">
            <Link href="/certificates/verify/demo" className="hover:text-primary transition-colors flex items-center space-x-1">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>Verify Certificate</span>
            </Link>
            <span className="opacity-40">|</span>
            <div className="flex items-center space-x-1 font-semibold text-emerald-400">
              <Activity className="w-3.5 h-3.5" />
              <span>Spring Boot REST API v1.0</span>
            </div>
          </div>
        </div>
      </div>

      {/* 2. Main Sticky Header (Porto Shrink & Navigation Architecture) */}
      <header className="sticky top-0 z-50 w-full border-b border-border bg-background/95 backdrop-blur-md shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 sm:h-20 flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center space-x-3 group">
            <div className="w-10 h-10 rounded bg-primary text-primary-foreground flex items-center justify-center font-display font-extrabold text-2xl shadow-md group-hover:scale-105 transition-transform">
              e
            </div>
            <div className="flex flex-col">
              <span className="font-display font-extrabold text-xl sm:text-2xl tracking-tight">
                eLearny<span className="text-primary">.LMS</span>
              </span>
              <span className="text-[10px] text-muted-foreground font-mono -mt-1 tracking-widest uppercase">Enterprise Platform</span>
            </div>
          </Link>

          {/* Navigation Links with Porto Active Line Indicator */}
          <nav className="hidden lg:flex items-center space-x-8 text-sm font-semibold text-foreground/80">
            <Link href="#features" className="nav-link-indicator hover:text-primary transition-colors py-1">Features</Link>
            <Link href="#disciplines" className="nav-link-indicator hover:text-primary transition-colors py-1">Disciplines</Link>
            <Link href="#proctoring" className="nav-link-indicator hover:text-primary transition-colors py-1">Proctoring</Link>
            <Link href="#faq" className="nav-link-indicator hover:text-primary transition-colors py-1">FAQ</Link>
          </nav>

          {/* Actions */}
          <div className="flex items-center space-x-3">
            <Link 
              href="/login"
              className="text-sm font-semibold text-foreground hover:text-primary px-3 py-2 transition-colors hidden sm:block"
            >
              Sign In
            </Link>
            <Link 
              href="/register"
              className="text-sm font-bold bg-primary text-primary-foreground px-5 py-2.5 rounded shadow-sm hover:opacity-90 transition-all flex items-center space-x-2"
            >
              <span>Get Started</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1">
        {/* 3. Hero Section with SVG Stroke Line Accents (Porto Parallax & Animation Pattern) */}
        <section className="relative pt-16 pb-28 md:pt-24 md:pb-36 bg-gradient-to-b from-muted/50 via-background to-background border-b border-border overflow-hidden">
          {/* Animated Background Watermark */}
          <div className="absolute top-10 left-1/2 -translate-x-1/2 text-[120px] sm:text-[180px] font-display font-black text-foreground/[0.03] select-none pointer-events-none tracking-widest">
            ELEARNY
          </div>

          {/* Background Gradient Glow */}
          <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[350px] bg-primary/10 blur-[130px] rounded-full pointer-events-none -z-10 animate-pulse-slow" />

          {/* SVG Vector Stroke Accents (Porto SVG Stroke Animation) */}
          <svg className="absolute top-0 right-0 w-96 h-96 opacity-20 pointer-events-none hidden md:block" viewBox="0 0 400 400" fill="none">
            <path d="M50 200 C 150 100, 250 300, 350 200" stroke="currentColor" strokeWidth="3" className="text-primary animate-svg-stroke" />
            <circle cx="200" cy="150" r="6" fill="currentColor" className="text-primary" />
            <circle cx="300" cy="220" r="4" fill="currentColor" className="text-primary" />
          </svg>

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
            <div className="text-center max-w-4xl mx-auto space-y-6">
              {/* Badge Pill */}
              <div className="inline-flex items-center space-x-2 bg-primary/10 border border-primary/20 px-4 py-1.5 rounded-full text-xs font-bold text-primary shadow-sm">
                <Sparkles className="w-3.5 h-3.5" />
                <span>Porto-Inspired Master Architecture • v1.0 Release</span>
              </div>

              {/* Title with Porto Highlight Box */}
              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-display font-extrabold tracking-tight text-foreground leading-[1.08]">
                Master High-Scale Engineering with <span className="custom-highlight-box">Production Rigor</span>
              </h1>

              {/* Subtitle */}
              <p className="text-base sm:text-lg md:text-xl text-muted-foreground leading-relaxed max-w-2xl mx-auto">
                An API-first learning platform built for modern developers. Stream HD video lectures, write code in Judge0 sandboxes, pass proctored exams, and earn QR-verifiable certificates.
              </p>

              {/* Action CTAs */}
              <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link
                  href="/register"
                  className="w-full sm:w-auto bg-primary text-primary-foreground font-bold px-8 py-3.5 rounded shadow-md hover:opacity-95 transition-all flex items-center justify-center space-x-2.5 text-base"
                >
                  <BookOpen className="w-5 h-5" />
                  <span>Start Learning Free</span>
                  <ArrowRight className="w-4 h-4 ml-1" />
                </Link>
                <Link
                  href="/login"
                  className="w-full sm:w-auto bg-background border border-border text-foreground font-bold px-8 py-3.5 rounded hover:bg-muted transition-colors flex items-center justify-center space-x-2.5 text-base shadow-sm"
                >
                  <PlayCircle className="w-5 h-5 text-primary" />
                  <span>Instructor Studio</span>
                </Link>
              </div>

              {/* Feature Chips */}
              <div className="pt-6 flex flex-wrap items-center justify-center gap-6 text-xs font-semibold text-muted-foreground">
                <span className="flex items-center space-x-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  <span>Razorpay One-Click Commerce</span>
                </span>
                <span className="flex items-center space-x-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  <span>Spring Boot 3.2 & Next.js 14</span>
                </span>
                <span className="flex items-center space-x-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  <span>Apache PDFBox Verification</span>
                </span>
              </div>
            </div>
          </div>
        </section>

        {/* 4. Porto Overlapping Callback/Quick Quote Card Pattern */}
        <section className="relative z-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-16 sm:-mt-24 mb-16">
          <div className="glass-card rounded-lg p-6 sm:p-8 shadow-xl border border-border bg-card/95">
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 items-center">
              <div className="lg:col-span-1 border-b lg:border-b-0 lg:border-r border-border pb-4 lg:pb-0 lg:pr-6">
                <span className="text-xs font-bold text-primary uppercase tracking-wider">Quick Advisor</span>
                <h3 className="text-xl font-display font-bold text-foreground mt-1">Request Learning Plan</h3>
                <p className="text-xs text-muted-foreground mt-1">Get a tailored course roadmap from our engineering team.</p>
              </div>

              <form className="lg:col-span-3 grid grid-cols-1 sm:grid-cols-3 gap-4" onSubmit={(e) => e.preventDefault()}>
                <div>
                  <label className="block text-[11px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Full Name</label>
                  <input 
                    type="text" 
                    placeholder="Alex Morgan" 
                    className="w-full px-3 py-2 text-sm border border-border rounded bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
                <div>
                  <label className="block text-[11px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Target Role</label>
                  <select className="w-full px-3 py-2 text-sm border border-border rounded bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-primary">
                    <option>Full-Stack Engineer</option>
                    <option>Spring Boot Microservices Architect</option>
                    <option>AI & Machine Learning Specialist</option>
                    <option>Cloud Security Engineer</option>
                  </select>
                </div>
                <div className="flex items-end">
                  <button 
                    type="submit" 
                    className="w-full bg-primary text-primary-foreground font-bold py-2 px-4 rounded hover:opacity-90 transition-opacity text-sm flex items-center justify-center space-x-1.5 shadow-sm"
                  >
                    <Send className="w-4 h-4" />
                    <span>Get Free Roadmap</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </section>

        {/* 5. Porto 4-Column Trust Badge Divider */}
        <section className="py-8 bg-muted/40 border-y border-border">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
              <div className="flex flex-col items-center space-y-1 p-3">
                <Users className="w-6 h-6 text-primary" />
                <span className="text-2xl font-display font-extrabold text-foreground">15,000+</span>
                <span className="text-xs text-muted-foreground font-medium">Active Engineers Enrolled</span>
              </div>
              <div className="flex flex-col items-center space-y-1 p-3">
                <BookOpen className="w-6 h-6 text-primary" />
                <span className="text-2xl font-display font-extrabold text-foreground">450+</span>
                <span className="text-xs text-muted-foreground font-medium">Production-Grade Courses</span>
              </div>
              <div className="flex flex-col items-center space-y-1 p-3">
                <ShieldCheck className="w-6 h-6 text-emerald-600" />
                <span className="text-2xl font-display font-extrabold text-emerald-600">99.4%</span>
                <span className="text-xs text-muted-foreground font-medium">Exam Pass Threshold</span>
              </div>
              <div className="flex flex-col items-center space-y-1 p-3">
                <Star className="w-6 h-6 text-amber-500 fill-amber-500" />
                <span className="text-2xl font-display font-extrabold text-foreground">4.92 / 5.0</span>
                <span className="text-xs text-muted-foreground font-medium">Verified Student Rating</span>
              </div>
            </div>
          </div>
        </section>

        {/* 6. Porto Feature Boxes Grid (.feature-box.feature-box-style-2) */}
        <section id="features" className="py-20 border-b border-border">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
              <span className="text-xs font-bold text-primary uppercase tracking-widest">Platform Core Features</span>
              <h2 className="text-3xl sm:text-4xl font-display font-bold">Engineered for Technical Mastery</h2>
              <p className="text-muted-foreground text-base">
                eLearny delivers high-performance learning components modeled after top software engineering environments.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Feature Box 1 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <PlayCircle className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">HD Progressive Video Player</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Cloudflare R2 signed URLs with responsive progressive range requests, custom playback speeds, and timestamped private lesson notes.
                </p>
              </div>

              {/* Feature Box 2 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <ShieldCheck className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">Automated Anti-Cheat Exams</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Browser-level integrity checks enforcing full-screen, tab-switch timestamp logging, and server-side timer/grading logic.
                </p>
              </div>

              {/* Feature Box 3 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <Award className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">QR Verifiable PDF Certification</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Apache PDFBox auto-generates credentials with unique verification codes accessible publicly for third-party validation.
                </p>
              </div>

              {/* Feature Box 4 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <Code className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">Judge0 Code Execution Sandbox</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Interactive in-browser code editor executing Python, Java, Rust, and C++ against unit tests inside self-hosted Judge0.
                </p>
              </div>

              {/* Feature Box 5 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <Zap className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">Razorpay One-Click Checkout</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Instant course and bundle purchasing supported by Razorpay webhook signature validation and coupon discount algorithms.
                </p>
              </div>

              {/* Feature Box 6 */}
              <div className="p-6 rounded border border-border bg-card hover:border-primary transition-all group space-y-4 shadow-sm">
                <div className="w-12 h-12 rounded bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  <Sparkles className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-display font-bold">AI Study & Recommendation Assistant</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  LLM-backed course discovery and student support powered by server-side Gemini Flash and Groq rate-limited prompts.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* 7. Disciplines & Filterable Course Showcase */}
        <section id="disciplines" className="py-20 border-b border-border bg-muted/20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
              <div>
                <span className="text-xs font-bold text-primary uppercase tracking-widest">Curriculum Categories</span>
                <h2 className="text-3xl font-display font-bold text-foreground mt-1">Explore High-Demand Disciplines</h2>
              </div>

              {/* Filter Tabs */}
              <div className="flex items-center space-x-2 mt-4 md:mt-0 overflow-x-auto pb-2 md:pb-0">
                {(['all', 'backend', 'ai', 'cloud'] as const).map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`px-4 py-1.5 rounded text-xs font-bold transition-all uppercase tracking-wider ${
                      activeTab === tab 
                        ? 'bg-primary text-primary-foreground shadow-sm' 
                        : 'bg-background border border-border text-foreground hover:border-primary'
                    }`}
                  >
                    {tab === 'all' ? 'All Disciplines' : tab === 'backend' ? 'Backend' : tab === 'ai' ? 'AI & ML' : 'Cloud & DevOps'}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                { title: 'Spring Boot 3.2 Microservices Architecture', level: 'Advanced', lessons: '42 Lessons', category: 'backend', rating: '4.95' },
                { title: 'Full-Stack Next.js 14 & React Masterclass', level: 'Intermediate', lessons: '38 Lessons', category: 'all', rating: '4.91' },
                { title: 'Large Language Models & Agentic Engineering', level: 'Featured', lessons: '29 Lessons', category: 'ai', rating: '4.98' },
                { title: 'Cloud Infrastructure & Kubernetes Security', level: 'Advanced', lessons: '35 Lessons', category: 'cloud', rating: '4.89' },
                { title: 'High-Performance Rust Systems Programming', level: 'Hardcore', lessons: '50 Lessons', category: 'backend', rating: '4.96' },
                { title: 'PostgreSQL Database Optimization & Tuning', level: 'Core', lessons: '24 Lessons', category: 'backend', rating: '4.92' },
              ]
              .filter(item => activeTab === 'all' || item.category === activeTab)
              .map((course, idx) => (
                <div key={idx} className="p-6 rounded border border-border bg-card hover:border-primary transition-all flex flex-col justify-between space-y-4 shadow-sm group">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="px-2.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-primary/10 text-primary border border-primary/20">
                        {course.level}
                      </span>
                      <div className="flex items-center space-x-1 text-xs font-bold text-amber-500">
                        <Star className="w-3.5 h-3.5 fill-amber-500" />
                        <span>{course.rating}</span>
                      </div>
                    </div>

                    <h3 className="font-display font-bold text-lg text-foreground group-hover:text-primary transition-colors leading-snug">
                      {course.title}
                    </h3>
                    <p className="text-xs text-muted-foreground">{course.lessons} • Hands-on Projects Included</p>
                  </div>

                  <div className="pt-4 border-t border-border flex items-center justify-between">
                    <span className="text-xs font-semibold text-muted-foreground">Self-Paced Learning</span>
                    <Link href="/register" className="text-xs font-bold text-primary group-hover:translate-x-1 transition-transform flex items-center space-x-1">
                      <span>Enroll Now</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </Link>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 8. Porto Modern Accordion FAQ Section */}
        <section id="faq" className="py-20 border-b border-border">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-12 space-y-2">
              <span className="text-xs font-bold text-primary uppercase tracking-widest">Got Questions?</span>
              <h2 className="text-3xl font-display font-bold">Frequently Asked Questions</h2>
            </div>

            <div className="space-y-4">
              {faqs.map((faq, idx) => (
                <div key={idx} className="border border-border rounded bg-card overflow-hidden transition-all shadow-sm">
                  <button
                    onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                    className="w-full p-5 text-left font-display font-bold text-base flex items-center justify-between text-foreground hover:text-primary transition-colors"
                  >
                    <span>{faq.q}</span>
                    <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform ${openFaq === idx ? 'rotate-180 text-primary' : ''}`} />
                  </button>
                  {openFaq === idx && (
                    <div className="px-5 pb-5 text-sm text-muted-foreground leading-relaxed border-t border-border/50 pt-3">
                      {faq.a}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 9. Porto CTA Section & Porto Ribbon Footer */}
        <section className="py-20 bg-primary/5 border-b border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-6">
            <h2 className="text-3xl sm:text-4xl font-display font-extrabold">Ready to Build Production-Grade Apps?</h2>
            <p className="text-muted-foreground text-base max-w-xl mx-auto">
              Join eLearny today and gain access to high-impact technical courses, live code sandboxes, and verifiable certificates.
            </p>
            <div>
              <Link
                href="/register"
                className="inline-flex items-center space-x-2 bg-primary text-primary-foreground font-bold px-8 py-4 rounded shadow-lg hover:opacity-95 transition-all text-base"
              >
                <span>Create Your Free Account</span>
                <ArrowRight className="w-5 h-5" />
              </Link>
            </div>
          </div>
        </section>
      </main>

      {/* Porto-Style Footer with Ribbon */}
      <footer className="relative bg-secondary text-white pt-16 pb-12 border-t border-white/10">
        {/* Porto Footer Ribbon Badge */}
        <div className="footer-ribbon hidden sm:block">
          <span>Get Certified Today</span>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-4 gap-10 mb-12">
          {/* Col 1 */}
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 rounded bg-primary text-primary-foreground flex items-center justify-center font-display font-bold text-lg">
                e
              </div>
              <span className="font-display font-bold text-xl">eLearny LMS</span>
            </div>
            <p className="text-xs text-white/70 leading-relaxed">
              Full-scale Learning Management System engineered with Spring Boot 3.2, Next.js 14, React Native Expo, and PostgreSQL.
            </p>
          </div>

          {/* Col 2 */}
          <div className="space-y-3">
            <h4 className="font-display font-bold text-sm text-primary uppercase tracking-wider">Quick Links</h4>
            <ul className="space-y-2 text-xs text-white/70">
              <li><Link href="#features" className="hover:text-white transition-colors">Platform Features</Link></li>
              <li><Link href="#disciplines" className="hover:text-white transition-colors">Course Disciplines</Link></li>
              <li><Link href="/certificates/verify/demo" className="hover:text-white transition-colors">Certificate Verification</Link></li>
              <li><Link href="/login" className="hover:text-white transition-colors">Instructor Portal</Link></li>
            </ul>
          </div>

          {/* Col 3 */}
          <div className="space-y-3">
            <h4 className="font-display font-bold text-sm text-primary uppercase tracking-wider">Disciplines</h4>
            <ul className="space-y-2 text-xs text-white/70">
              <li>Full-Stack Web Engineering</li>
              <li>Spring Boot Microservices</li>
              <li>AI & Agentic Engineering</li>
              <li>Cloud & DevOps Security</li>
            </ul>
          </div>

          {/* Col 4 - Newsletter Form */}
          <div className="space-y-3">
            <h4 className="font-display font-bold text-sm text-primary uppercase tracking-wider">Stay Updated</h4>
            <p className="text-xs text-white/70">Subscribe for new course alerts and engineering tutorials.</p>
            <form className="flex" onSubmit={(e) => e.preventDefault()}>
              <input 
                type="email" 
                placeholder="Enter email address..." 
                className="w-full px-3 py-2 text-xs bg-white/10 border border-white/20 rounded-l text-white placeholder:text-white/50 focus:outline-none"
              />
              <button type="submit" className="bg-primary px-3 py-2 rounded-r text-white hover:opacity-90">
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 border-t border-white/10 pt-6 flex flex-col sm:flex-row items-center justify-between text-xs text-white/60 gap-4">
          <p>© {new Date().getFullYear()} eLearny Inc. All rights reserved.</p>
          <div className="flex items-center space-x-4">
            <Link href="/privacy" className="hover:text-white">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-white">Terms of Use</Link>
            <span className="flex items-center space-x-1 text-emerald-400 font-semibold">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
              <span>Platform Systems Normal</span>
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
